---
title: "Untitled"
author: "oushiei"
date: "2023-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 7.correspondence analysis

```{r}
suppressPackageStartupMessages({
  library(quanteda.textstats)
  library(readtext)
  library(tidyverse)
  library(tidytext)
  library(showtext)
  require(quanteda)
  require(quanteda.textmodels)
  require(quanteda.textplots)
  library(factoextra)
})
source("/Users/oushiei/Desktop/论文终稿/finalcode/font and theme.R")
```

```{r}
v0 <- readtext("/Users/oushiei/Desktop/论文终稿/finalcode/data/3_6_seg",docvarsfrom = "filenames") %>% corpus() %>% tokens(what="fasterword")
renshi_dfm <- tokens_select(v0, c("和","跟","与","同","及","而","况","况且","何况","乃至","则","乃","就","而","于是","至于","说到","此外","像","如","一般","比方",
                           "却","但是","然而","而","偏偏","只是","不过","至于","致","不料","岂知",
                           "原来","因为","由于","以便","因此","所以","是故","以致",
                           "或","抑",
                           "若","如果","若是","假如","假使","倘若","要是","譬如",
                           "像","好比","如同","似乎","等于","不如","不及","与其","不如",
                           "虽然","固然","尽管","纵然","即使"), selection = "keep", padding = F) %>% dfm()
#==========
# dfm
#==========

docnames(renshi_dfm) <- docvars(v0,"docvar1")

csv <- renshi_dfm %>% convert(to="data.frame")
dim(csv)
write.csv(t(csv),"/Users/oushiei/Desktop/论文终稿/finalcode/data for print/対応分析用.csv")


tmod_ca <- textmodel_ca(renshi_dfm)

#==========
# 
#==========

fviz_ca_biplot(tmod_ca, label =c("row"),
               shape.row=3,shape.col=2,
               labelsize = 5, pointsize = 2, 
               col.col = "red", repel = TRUE
)+
xlim(-0.8, 0.8) +
ylim (-0.5, 0.5)+
 theme_ou()

#==========
# 
#==========
fviz_ca_biplot(tmod_ca, label =c("col"),
               shape.row=3,shape.col=2,
               labelsize = 5, pointsize = 2, 
               col.col = "red", repel = TRUE
)+
xlim(-0.8, 0.8) +
ylim (-0.5, 0.5)+
 theme_ou()


#==========
# 
#==========

renshi_dfm

dist_tmp = dfm_weight(renshi_dfm, scheme = "prop") %>% convert(to="data.frame")
dist_tmp

rownames(dist_tmp) <- dist_tmp$doc_id
dist_tmp$doc_id <- NULL
dist_tmp

tree <- dist_tmp%>% 
  dist() %>% 
  hclust()

dend <- tree %>% 
  as.dendrogram()

```

